---
title: "Introduction to Quarto"
title-slide-attributes:
    data-background-gradient: "radial-gradient(#FB8500, #FD9E02, #FFB703)"
    data-background-size: contain
    data-background-opacity: "0.5"
author: Andrew Zieffler
date: "`r format(Sys.Date(), '%B %d %Y')`"
format: 
  revealjs:
    smaller: true
    scrollable: true
    chalkboard: true
    theme: "simple"
---

## What is Quarto?

Quarto® is an open-source scientific and technical publishing system built on Pandoc. For us, it allows us to embed R syntax directly in a text document. Using Quarto is one of the first steps to making your research more reproducible. By integrating your R syntax and your text into a single document, it also improves your analytical workflow.


## Similar to RMarkdown...But Better

For those of you familiar with RMarkdown, Quarto® is a multi-language, next generation version of R Markdown from RStudio, with many new new features and capabilities. Like R Markdown, Quarto® uses Knitr to execute R code, and is therefore able to render most existing Rmd files without modification.


## Install Quarto

1.  Head over to <https://quarto.org/> and click on the big, blue "Get Started" button. Then follow the instructions to install Quarto.
2.  Open RStudio. (Note if RStudio was open when you installed Quarto, quit and re-open it.)

At this point in RStudio, if you go to `File > New File...` you should see options to choose `Quarto Document` and `Quarto Presentation`.

## Help and Tutorials

There are several [guides and tutorials](https://quarto.org/docs/guide/) available on the Quarto website. These include:

-   Creating basic content (e.g., figures, tables, diagrams, footnotes, citations)
-   Including computation/syntax
-   Generating output in different formats (e.g., HTML, PDF, MS Word)
-   Creating slides and presentations (These notes are a Quarto presentation!)
-   Building websites
-   Building books
-   Creating interactive dashboards

## Create Your First Quarto Document

Click the [Tutorial: Hello Quarto](https://quarto.org/docs/get-started/hello/rstudio.html) link on the left-side of the "Getting Started" page. Make sure that the RStudio tool is selected at the top of the tutorial.

<br />

Work through this tutorial with a neighbor. This will introduce you to some of the basic concepts of creating and rendering a Quarto document.

## Learning How to Integrate R Code

Work through the [Tutorial: Computations](https://quarto.org/docs/get-started/computations/rstudio.html) with your neighbor. Again, before starting, ensure that the RStudio tool is selected at the top of the tutorial.


## Install a Citation Manager

For next class you will need a citation manager. If you don't have a citation manager, I strongly recommend Zotero.

-   Install [Zotero](https://www.zotero.org/).

If you use a different citation manager, you will need to figure out how to export a .BIB file from your citation manager.


## Project and File Management

Before next class, also look at your computer files and your organization of those files. Here are some things to reflect on:

- Are your files organized into folders/directories? Or are they all in your Downloads folder?
  + How did you organize all the data files, notes, etc. from EPsy 8251?
- If I asked you to find a specific file, could you locate it without using "Search"?
- Can you tell what is in a particular file by just looking at its name?
- Do your file names contain spaces? What about characters that aren't letters, numbers, dashes, or underscores?
- Are your file names consistent (all lower case letters, or all title case)? Or are they all different?




